add_newline = false
scan_timeout = 10
format = '${env_var.PROJECT}$all'

[custom.direnv]
format = "[\\(direnv\\)]($style) "
style = "red"
when = "env | grep -E '^DIRENV_FILE='"

[env_var.PROJECT]
format = "[✳️  $env_value]($style): "
style = "green"
variable = 'PROJECT'
# when = "env | grep -E '^PROJECT='"

[battery]
[[battery.display]]
style = "bold red"
threshold = 15

[[battery.display]]
style = "bold yellow"
threshold = 30

[character]
error_symbol = "[λ](bold red)"
success_symbol = "[λ](bold green)"
vicmd_symbol = "[λ](bold blue)"

[conda]
disabled = true

[directory]
truncation_length = 8
truncation_symbol = "…/"

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[gcloud]
format = "on [($symbol$project)]($style) "

[git_status]
modified = "*"
renamed = "R"

[nodejs]
disabled = true

[ocaml]
disabled = true

[php]
disabled = true

[status]
disabled = false
format = "[[$symbol$status]]($style) "
style = "bg:blue"

[kubernetes]
format = '[⛵ $context ](green)'
disabled = false
