#!/usr/bin/env bash

set -e

case "$1" in
  lock)
      swaylock
      ;;
  logout)
      swaymsg exit
      ;;
  suspend)
      systemctl suspend
      ;;
  reboot)
      systemctl reboot
      ;;
  shutdown)
      systemctl poweroff
      ;;
  *)
      echo "== ! i3exit: missing or invalid argument ! =="
      echo "Try again with: lock | logout | suspend | reboot | shutdown"
      exit 2
esac


