#!/usr/bin/env bash

DATE=date

h \
  -s bal \
  --pretty-tables \
  --budget -E \
  ^exp ^equity:adj \
  not:tag:clopen \
  -b $($DATE +%Y-%m --date="last month") \
  -e $($DATE +%Y-%m --date="next month") \
  -M --real $@ | rg -v 'Budget performance' | rg --color=always --passthru '\d\d\d%'
