#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8

normalize_padding() {
    percent_len=${#1}
    max_len=${2:-5}
    let diff_len=$max_len-$percent_len
    # if the diff_len is even, left will have 1 more space than right
    let left_spaces=($diff_len + 1)/2
    let right_spaces=($diff_len)/2
    printf "%${left_spaces}s%s%${right_spaces}s\n" "" $1 ""
}

get_percent() {
    case $(uname -s) in
    Linux)
        if [ -z $TERMUX_VERSION ]; then
            percent=$(LC_NUMERIC=en_US.UTF-8 top -bn2 -d 0.01 | grep "Cpu(s)" | tail -1 | sed "s/.*, *\([0-9]*\)\.[0-9]*%* id.*/\1/" | awk '{print 100 - $1}')
            echo $percent
        else
            echo "0"
        fi
        ;;

    Darwin)
        cpuvalue=$(/bin/ps -A -o %cpu | awk -F. '{s+=$1} END {print s}')
        cpucores=$(sysctl -n hw.logicalcpu)
        cpuusage=$((cpuvalue / cpucores))
        echo $cpuusage
        ;;

    CYGWIN* | MINGW32* | MSYS* | MINGW*) ;; # TODO - windows compatibility
    esac
}

main() {
    cpu_label=""
    cpu_percent=$(get_percent)
    if [ -n "$cpu_percent" ]; then
        # Store raw percent for comparison
        cpu_raw=$cpu_percent
        cpu_percent=$(normalize_padding "$cpu_percent%")

        # Color based on usage
        if [ $cpu_raw -gt 90 ]; then
            echo "#[fg=#{{ conf.colors.base08 }}]$cpu_label ${cpu_percent}"
        else
            echo "#[fg=#{{ conf.colors.base0C }}]$cpu_label ${cpu_percent}"
        fi
    fi
}

main
