#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8

HOSTS="google.com github.com example.com"

# Patch for Orb
if [[ "$ORB" == "true" ]];then
    MAC_PREFIX="/opt/orbstack-guest/bin/mac"
    PLATFORM="Darwin"
else
    MAC_PREFIX=""
    PLATFORM=$(uname -s)
fi

get_ssid() {
    case $PLATFORM in
    Linux)
        if [ -z $TERMUX_VERSION ]; then
            SSID=$(iwgetid -r)
            if [ -n "$SSID" ]; then
                printf '%s' " $SSID"
            else
                echo '󰈀 '
            fi
        else
            echo 'n/a'
        fi
        ;;

    Darwin)
        device_name=$($MAC_PREFIX networksetup -listallhardwareports | grep -A 1 Wi-Fi | grep Device | awk '{print $2}')
        SSID=$($MAC_PREFIX networksetup -getairportnetwork "$device_name" | awk -F ": " '{print $2}')
        if [ -n "$SSID" ]; then
            printf '%s' " $SSID"
        else
            echo '󰈀 '
        fi
        ;;

    CYGWIN* | MINGW32* | MSYS* | MINGW*) ;; # TODO - windows compatability
    esac
}

main() {
    network="Offline"
    for host in $HOSTS; do
        if curl -Is $host 2>/dev/null | grep -q HTTP; then
            network="#[fg=#{{ conf.colors.base0B }}]$(get_ssid)"
            break
        fi
    done

    echo "$network"
}

main
