add_newline = false
scan_timeout = 10
# format = '${env_var.PROJECT}$all'

palette = 'my'

[palettes.my]
black = '#{{ conf.colors.base00 }}'
red = '#{{ conf.colors.base08 }}'
green = '#{{ conf.colors.base0B }}'
blue = '#{{ conf.colors.base0D }}'
yellow = '#{{ conf.colors.base0A }}'
purple = '#{{ conf.colors.base0E }}'
cyan = '#{{ conf.colors.base0C }}'
white = '#{{ conf.colors.base05 }}'
bright-black = '#{{ conf.colors.base03 }}'
bright-red = '#{{ conf.colors.base09 }}'
bright-green = '#{{ conf.colors.base01 }}'
bright-blue = '#{{ conf.colors.base04 }}'
bright-yellow = '#{{ conf.colors.base02 }}'
bright-purple = '#{{ conf.colors.base06 }}'
bright-cyan = '#{{ conf.colors.base0F }}'
bright-white = '#{{ conf.colors.base07 }}'

[custom.direnv]
format = "[\\(d\\)]($style) "
style = "red"
when = "env | grep -E '^DIRENV_FILE='"

# [env_var.PROJECT]
# format = "[✳️  $env_value]($style): "
# style = "green"
# variable = 'PROJECT'
# # when = "env | grep -E '^PROJECT='"

[battery]
[[battery.display]]
style = "bold red"
threshold = 15

# [[battery.display]]
# style = "bold yellow"
# threshold = 30

[character]
error_symbol = "[λ](bold red)"
success_symbol = "[λ](bold green)"
vicmd_symbol = "[λ](bold blue)"

[conda]
disabled = true

[directory]
truncation_length = 8
truncation_symbol = "…/"

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[gcloud]
format = "on [($symbol$project)]($style) "

[git_status]
modified = "*"
renamed = "R"

[nodejs]
disabled = true

[ocaml]
disabled = true

[php]
disabled = true

[status]
disabled = false
format = "[[$symbol$status]]($style) "
style = "bg:blue"

[kubernetes]
symbol = "⛵ "
format = '[$symbol$context:$namespace]($style) '
disabled = false
contexts = [
    { context_pattern =  ".*-prod(?P<cluster>[\\w-]+)-cluster", style = "red bold", context_alias = "prod$cluster" },
    { context_pattern =  ".*-(?P<cluster>[\\w-]+)-cluster", style = "green bold", context_alias = "$cluster" },
]
