if status is-interactive
  set -gx _git_log_medium_format '%C(bold)Commit:%C(reset) %C(green)%H%C(red)%d%n%C(bold)Author:%C(reset) %C(cyan)%an <%ae>%n%C(bold)Date:%C(reset)   %C(blue)%ai (%ar)%C(reset)%n%+B'
  set -gx _git_log_oneline_format '%C(green)%h%C(reset) %s%C(red)%d%C(reset)%n'
  set -gx _git_log_brief_format '%C(green)%h%C(reset) %s%n%C(blue)(%ar by %an)%C(red)%d%C(reset)%n'
  set -gx _git_log_some '%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset'
end

function __git_abbr_init

  if test "$__git_abbr_inited" = 1
    return
  end

  set -g __git_abbr_inited 1

  abbr -a ga     'git add'
  abbr -a gA     'git cherry-pick --no-commit'
  abbr -a gAF    'git cherry-pick --ff'
  abbr -a gb     'git branch'
  abbr -a gba    'git branch --all --verbose'
  abbr -a gbc    'git switch -c'
  abbr -a gbD    'git branch --delete'
  abbr -a gbs    'git switch'
  abbr -a gbX    'git branch --delete --force'
  abbr -a gc     'git commit --verbose'
  abbr -a gcam   'git commit --verbose --amend'
  abbr -a gcm    'git commit --message'
  abbr -a gco    'git checkout'
  abbr -a gdc    'git diff --no-ext-diff --cached'
  abbr -a gd     'git diff --no-ext-diff'
  abbr -a gfa    'git fetch --all'
  abbr -a gf     'git fetch'
  abbr -a g      git
  abbr -a glb    'git log --topo-order --pretty=format:"$_git_log_brief_format"'
  abbr -a glC    'git shortlog --summary --numbered'
  abbr -a gldiff 'git log --topo-order --stat --patch --full-diff --pretty=format:"$_git_log_medium_format"'
  abbr -a glga   'git log --topo-order --graph --pretty=format:"$_git_log_oneline_format" --all'
  abbr -a glgas  'git log --topo-order --graph --pretty=format:"$_git_log_oneline_format" --all --stat'
  abbr -a glg    'git log --topo-order --graph --pretty=format:"$_git_log_oneline_format"'
  abbr -a gl     'git log --topo-order --pretty=format:"$_git_log_medium_format"'
  abbr -a glgsa  'git log --topo-order --graph --pretty=format:"$_git_log_oneline_format" --stat --all'
  abbr -a glgs   'git log --topo-order --graph --pretty=format:"$_git_log_oneline_format" --stat'
  abbr -a gloga  'git log --date=short --graph --pretty="$_git_log_some" --all'
  abbr -a glogat 'git log --graph --pretty="$_git_log_some" --all'
  abbr -a glog   'git log --date=short --graph --pretty="$_git_log_some"'
  abbr -a glo    'git log --topo-order --pretty=format:"$_git_log_oneline_format"'
  abbr -a glogta 'git log --graph --pretty="$_git_log_some" --all'
  abbr -a glogt  'git log --graph --pretty="$_git_log_some"'
  abbr -a glS    'git log --show-signature'
  abbr -a gls    'git log --topo-order --stat --pretty=format:"$_git_log_medium_format"'
  abbr -a gma    'git merge --abort'
  abbr -a gmC    'git merge --no-commit'
  abbr -a gmf    'git merge --ff-only'
  abbr -a gmF    'git merge --no-ff'
  abbr -a gm     'git merge'
  abbr -a gmSf   'git merge -S --ff-only'
  abbr -a gmS    'git merge -S'
  abbr -a gms    'git merge --squash'
  abbr -a gmSs   'git merge -S --squash'
  abbr -a gPa    'git push --all'
  abbr -a gPat   'git push --all && git push --tags'
  abbr -a gPF    'git push --force'
  abbr -a gPf    'git push --force-with-lease'
  abbr -a gP     'git push'
  abbr -a gpra   'git pull --rebase --autostash'
  abbr -a gpr    'git pull --rebase'
  abbr -a gPta   'git push --all && git push --tags'
  abbr -a gPt    'git push --tags'
  abbr -a gp     'git pull'
  abbr -a gra    'git rebase --abort'
  abbr -a grc    'git rebase --continue'
  abbr -a gRf    'git restore --source='
  abbr -a gr     'git rebase'
  abbr -a gR     'git restore'
  abbr -a gri    'git rebase --interactive'
  abbr -a gRp    'git restore --patch'
  abbr -a grs    'git rebase --skip'
  abbr -a gRs    'git restore --staged'
  abbr -a gs     'git status'
  abbr -a gt     'git tag'
  abbr -a gtl    'git tag -l'
  abbr -a gts    'git tag -s'
  abbr -a gwa    'git worktree add'
  abbr -a gwl    'git worktree list'
  abbr -a gwm    'git worktree move'
  abbr -a gwp    'git worktree prune'
  abbr -a gwx    'git worktree remove'
  abbr -a gXC    'git clean -e shell.nix -e .envrc -dxf'
  abbr -a gXc    'git clean -e shell.nix -e .envrc -dxn'
  abbr -a gX     'git reset'
  abbr -a gXh    'git reset --hard'
  abbr -a gXH    'git reset "HEAD^"'
  abbr -a gXs    'git reset --soft'
  abbr -a gXX    'git rm -r --cached'
  abbr -a gZa    'git stash apply'
  abbr -a gZd    'git stash drop'
  abbr -a gZ     'git stash'
  abbr -a gZl    'git stash list'
  abbr -a gZp    'git stash pop'
  abbr -a gZs    'git stash save --include-untracked'
  abbr -a gZS    'git stash save --patch --no-keep-index'

end

__git_abbr_init
