#!/usr/bin/ansible-playbook -v
---

- name: Removing
  become: false
  hosts: "{{ server }}"
  tasks:

    - name: remove configs
      file: path={{ item }} state=absent
      with_items:
          - "~/.art"
          - "~/.tmux-art"
          - "~/.zshrc-art"
          - "~/.zsh_history-art"
