#!/usr/bin/env bash

if [ -n "$TMUX" ]
then
    I=$(T=$(tty)
    tmux lsp -F'#{pane_tty} #{pane_index}' |grep ^$T | cut -f2 -d' ')
    ALL=$(tmux lsp | wc -l)

    if [ $((ALL-I)) -le 1 ]
    then
        I=$(($I-1))
    fi
    tmux split-window -l 40% -h -t $((I+1)) 
else
    $SHELL
fi
